name: 02 - Workflow Events

on: 
  push:
  pull_request:
  schedule:
    - cron: '10 * * * *'

jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger 
        run: echo "push"
