name: 02 - Workflow Events

on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger 
        run: echo "push"
  log-level:
    runs-on: ubuntu-latest
    steps:
      - name: print log level
        run: echo log level information ${{ inputs.loglevel }}
