name: 02 - Workflow Events

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger 
        run: echo "push"
  log-level:
    runs-on: ubuntu-latest
    if: inputs.loglevel != ''
    steps:
      - name: print log level
        run: echo log level information ${{ inputs.loglevel }}
