name: 06 - Contexts

on:
  workflow_dispatch:
  push:

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: display information 
        run: |
          echo "Event name: ${{github.name}}"
          echo "REF: ${{github.ref}}"
          echo "SHA: ${{github.sha}}"
          echo "Actor: ${{github.actor}}"

