name: 07 - Using Expressions

on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: bool value that determines whether to print information

jobs:
  echo-expressions:
    runs-on: ubuntu-latest
    if: ${{ inputs.debug == true}}
    steps:
      - name: debug Print start-up data
        run: |
          echo "Triggered by: ${{ github.triggering_actor }} - ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"

    