name: 07 - Using Expressions

run-name: 07 - Using expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: bool value that determines whether to print information
  
jobs:
  echo-expressions:
    runs-on: ubuntu-latest
    
    steps:
      - name: debug Print start-up data
        if: inputs.debug == true
        run: |
          echo "Triggered by: ${{ github.triggering_actor }} - ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: debug Print when triggered from main
        if: inputs.debug == true && github.ref_name == 'main'
        run: echo "I was triggered by main"
      - name: Greetings
        run: echo "Hello World"

    
