name: 12 - Working with Outputs

on: 
  workflow_dispatch:
    build-status:
      type: choice
      options: [failure, success]
      default: success

jobs:
  build:
    runs-on: ubuntu-latest
    output:
      build-status: ${{ GITHUB_OUTPUT.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "GITHUB_OUTPUT: ${{ GITHUB_OUTPUT }}"
      - name: Build
        id: build
        run:  cat "status = ${{ inputs.build-status }}">> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.output.build-status == success }}
    steps:
      - name: Deploy
        run: echo "Deploying artifacts"

